SEARCH_QUERIES = [
    "fight scene", "best fight", "best scene", "best fight scene",
    "epic fight", "epic scene", "epic fight scene", "top fight", "top scene",
    "top fight scene", "cool fight", "cool scene", "cool fight scene", "action fight",
    "action scene", "action fight scene", "martial arts fight", "martial arts scene",
    "martial arts fight scene", "superhero fight", "superhero scene", "superhero fight scene",
    "sci-fi fight", "sci-fi scene", "sci-fi fight scene", "fantasy fight", "fantasy scene",
    "fantasy fight scene", "spy fight", "spy scene", "spy fight scene", "samurai fight",
    "samurai scene", "samurai fight scene", "horror fight", "horror scene", "horror fight scene",
    "ninja fight", "ninja scene", "ninja fight scene", "kung fu fight", "kung fu scene",
    "kung fu fight scene", "movie fight", "movie scene", "movie fight scene",
    "best action fight", "best action scene", "best action fight scene",
    "best martial arts fight", "best martial arts scene", "best martial arts fight scene",
    "best superhero fight", "best superhero scene", "best superhero fight scene",
    "best sci-fi fight", "best sci-fi scene", "best sci-fi fight scene",
    "best fantasy fight", "best fantasy scene", "best fantasy fight scene",
    "best spy fight", "best spy scene", "best spy fight scene", "best samurai fight",
    "best samurai scene", "best samurai fight scene", "best horror fight",
    "best horror scene", "best horror fight scene", "best ninja fight", "best ninja scene",
    "best ninja fight scene", "best kung fu fight", "best kung fu scene",
    "best kung fu fight scene", "best movie fight", "best movie scene",
    "best movie fight scene", "epic action fight", "epic action scene",
    "epic action fight scene", "epic martial arts fight", "epic martial arts scene",
    "epic martial arts fight scene", "epic superhero fight", "epic superhero scene",
    "epic superhero fight scene", "epic sci-fi fight", "epic sci-fi scene",
    "epic sci-fi fight scene", "epic fantasy fight", "epic fantasy scene",
    "epic fantasy fight scene", "epic spy fight", "epic spy scene", "epic spy fight scene",
    "epic samurai fight", "epic samurai scene", "epic samurai fight scene",
    "epic horror fight", "epic horror scene", "epic horror fight scene",
    "epic ninja fight", "epic ninja scene", "epic ninja fight scene",
    "epic kung fu fight", "epic kung fu scene", "epic kung fu fight scene",
    "epic movie fight", "epic movie scene", "epic movie fight scene",
    "top action fight", "top action scene", "top action fight scene",
    "top martial arts fight", "top martial arts scene", "top martial arts fight scene",
    "top superhero fight", "top superhero scene", "top superhero fight scene",
    "top sci-fi fight", "top sci-fi scene", "top sci-fi fight scene",
    "top fantasy fight", "top fantasy scene", "top fantasy fight scene",
    "top spy fight", "top spy scene", "top spy fight scene", "top samurai fight",
    "top samurai scene", "top samurai fight scene", "top horror fight",
    "top horror scene", "top horror fight scene", "top ninja fight", "top ninja scene",
    "top ninja fight scene", "top kung fu fight", "top kung fu scene",
    "top kung fu fight scene", "top movie fight", "top movie scene",
    "top movie fight scene", "cool action fight", "cool action scene",
    "cool action fight scene", "cool martial arts fight", "cool martial arts scene",
    "cool martial arts fight scene", "cool superhero fight", "cool superhero scene",
    "cool superhero fight scene", "cool sci-fi fight", "cool sci-fi scene",
    "cool sci-fi fight scene", "cool fantasy fight", "cool fantasy scene",
    "cool fantasy fight scene", "cool spy fight", "cool spy scene", "cool spy fight scene",
    "cool samurai fight", "cool samurai scene", "cool samurai fight scene",
    "cool horror fight", "cool horror scene", "cool horror fight scene",
    "cool ninja fight", "cool ninja scene", "cool ninja fight scene",
    "cool kung fu fight", "cool kung fu scene", "cool kung fu fight scene",
    "cool movie fight", "cool movie scene", "cool movie fight scene"
]

SYNONYMS = {
    'fight': ['battle', 'clash', 'brawl', 'scuffle', 'duel'],
    'gym': ['fitness center', 'workout studio', 'training arena', 'exercise hall'],
    'cable': ['machine', 'equipment', 'device'],
    'machine': ['equipment', 'apparatus', 'device'],
    'win': ['triumph', 'victory', 'succeed'],
    'winner': ['champion', 'victor', 'conqueror'],
    'fighting': ['combat', 'boxing', 'wrestling', 'martial arts'],
    'fighter': ['combatant', 'warrior', 'brawler', 'contender'],
    'shorts': ['clips', 'reels', 'snippets'],
    'viral': ['trending', 'popular', 'buzzing'],
}